spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 224422
  jpa:
    hibernate:
      ddl-auto: update    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
      show-sql: false  
      
        